const $ = s => document.querySelector(s);
const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 library:'<rect x="3" y="6" width="18" height="14" rx="3"/><path d="M7 3h10m-7 7 5 3-5 3z"/>',
 target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 plus:'<circle cx="12" cy="12" r="9"/><path d="M12 8v8m-4-4h8"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 5v2"/>',
 arrow:'<path d="M7 17 17 7M7 7h10v10"/>',
 right:'<path d="m9 5 7 7-7 7"/>',
 back:'<path d="m15 5-7 7 7 7"/>',
 play:'<circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/>',
 ball:'<circle cx="12" cy="12" r="9"/><path d="M5 5c7 0 7 14 14 14M19 5C12 5 12 19 5 19"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5"/>',
 book:'<path d="M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3zm9 2v16"/>',
 trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>'
};
const icon = n => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n] || paths.ball}</svg>`;
const time = n => { const s = Math.floor(n); return `${s >= 3600 ? Math.floor(s/3600)+':' : ''}${s >= 3600 ? String(Math.floor(s/60)%60).padStart(2,'0') : Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`; };
const date = n => new Date(n).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const privacy = () => `<div class="privacy">${icon('lock')} On-device video. Simulated insights.</div>`;
const hero = (welcome=false) => `<div class="hero"><div class="court"><div class="net"></div></div><div class="tennis-ball"></div><span class="pill">${welcome?'THE NEXT CHAPTER OF YOUR GAME':'YOUR GAME, IN FOCUS'}</span><div class="hero-copy"><h2>${welcome?'Every session.<br>A fresh perspective.':'A little review.<br>A lot to play for.'}</h2><p>Your private space to become a better player.</p></div></div>`;
const notice = () => `<div class="notice"><strong>Sample coaching, clearly labeled.</strong>Random statistics and timestamps, not video analysis or detected mistakes. Use your own observations to assess your game.</div>`;
let db, sessions=[], profile=null, saved=[], current='welcome', activeID=null, activeKey=null, filter='All', query='', guest=false, authMode='create', controller=null, busy=false, playerURL=null, flowID=0;
const open = indexedDB.open('ace-pro-device-v1',1);
open.onupgradeneeded = () => { open.result.createObjectStore('data'); };
db = await new Promise((resolve,reject)=>{open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error)}).catch(error=>{ $('#app').textContent='Local storage is unavailable. Enable browser storage and reload. '+error.message; throw error; });
const read = key => new Promise((resolve,reject)=>{ const r=db.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error); });
const write = (key,value) => new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Storage cancelled'));});
const remove = key => new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});
function saveVideo(session,blob){return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite'),data=tx.objectStore('data');data.put(blob,'video:'+session.id);data.put([session,...sessions],'sessions');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Could not save this video. Check available storage.'));});}
async function reload(){sessions=await read('sessions')||[];profile=await read('profile')||null;saved=await read('saved')||[];}
await reload();
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500);}
const button=(action,text,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
function shell(content){
 const detail=['report','insight'].includes(current), title=current==='report'?'Session review':current==='insight'?'Coaching detail':'';
 $('#app').innerHTML=`<div class="desktop"><aside class="intro"><div class="brand"><span class="ball">◉</span> ACE PRO</div><h1>Your game.<br>Your next best.</h1><p>A private tennis video journal.<br>Designed for the moments that make you better.</p><span class="eyebrow">iOS EXPERIENCE · LOCAL PREVIEW</span><p style="font-size:11px">Videos stay in this browser. The native iOS app stores them on your phone.</p></aside><main class="phone"><div class="status"><span>${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</span><div class="island"></div><span class="status-right">▮▮▮ ▰</span></div><header class="topbar">${detail?button(current==='report'?'library':'report',icon('back')+' Back','back'):'<div class="brand" style="font-size:12px;letter-spacing:3px">'+icon('ball')+' ACE PRO</div>'}${detail?`<b style="font-size:12px">${title}</b>`:current==='welcome'?'<span class="eyebrow" style="font-size:8px">PLAY. REFLECT. GROW.</span>':button('profile',escape((guest?'P':profile?.name?.[0]||'P').toUpperCase()),'avatar','aria-label="Your profile"')}</header><section class="content ${current==='welcome'?'welcome':''}">${content}</section>${current!=='welcome'?`<nav class="tabs" aria-label="Main navigation">${[['home','sun','Today'],['library','library','Library'],['improve','target','Improve'],['profile','user','Profile']].map(([action,i,text])=>button(action,icon(i)+text,'tab '+(current===action?'active':''),current===action?'aria-current="page"':'')).join('')}</nav>`:''}<div class="home-indicator"></div></main><aside class="aside"><span class="eyebrow">A BETTER BETWEEN-POINTS</span><div style="height:25px"></div><div class="step"><b>01 &nbsp; Bring your game</b><small>Match or practice. Your videos stay with you, always.</small></div><div class="step"><b>02 &nbsp; Find your focus</b><small>Explore sample insights, revisit moments, and add your observations.</small></div><div class="step"><b>03 &nbsp; Take it to the court</b><small>Save a drill. Build a habit.<br>Come back stronger.</small></div><p style="font-size:10px">Experience preview. Coaching insights are randomly generated, not measured from footage.</p></aside></div>`;
}
function sessionRow(s){return button('open-report',`<span class="thumb">${icon(s.type==='Match'?'ball':'play')}</span><span><strong>${escape(s.title)}</strong><small>${escape(s.type)} · ${date(s.date)} · ${time(s.duration)}</small><span class="ready">${s.report?'Sample report ready':'Saved locally · ready for insights'}</span></span>${icon('right')}`,'card session',`data-id="${s.id}"`)}
function empty(title,text,i='library'){return `<div class="card empty">${icon(i)}<h3>${title}</h3><p>${text}</p></div>`}
function render(){
 const s=sessions.find(s=>s.id===activeID);
 if(['report','insight'].includes(current)&&!s)current='library';
 let html='';
 if(current==='welcome')html=`${hero(true)}<h1>Your game.<br>A clearer perspective.</h1><p class="muted">Keep your videos close. Review the moments.<br>Build a better next session.</p>${button('signup','Create a device account')}${button('login','I already have an account','secondary')}${button('guest','Explore without an account →','plain')}<p class="caption muted">Random coaching examples, not video analysis. Accounts are local to this device, with no cloud login or recovery.</p>`;
 if(current==='home')html=`<p class="greeting">Good to see you, ${escape(guest?'player':profile?.name?.split(' ')[0]||'player')}.</p><h1>Let’s build<br>your next best.</h1>${hero()}${button('add',icon('plus')+' Add a tennis video')}${privacy()}<div class="stats"><div class="stat">${icon('library')}<strong>${sessions.length.toString().padStart(2,'0')}</strong><span>Sessions in your library</span></div><div class="stat">${icon('target')}<strong>${saved.length.toString().padStart(2,'0')}</strong><span>Drills in your practice plan</span></div></div><div class="section-head"><h2>Your latest session</h2>${button('library','View all','plain')}</div>${sessions.length?sessionRow(sessions[0]):empty('Every improvement starts somewhere','Add a match or practice video to start your personal collection.','ball')}<div class="tiny-card"><div class="eyebrow">01 REVIEW &nbsp; → &nbsp; 02 PRACTICE &nbsp; → &nbsp; 03 REPEAT</div><h3>One focus is enough.</h3><p>Pick one cue, take it to the court, and notice what changes.</p></div>`;
 if(current==='library'){
 const list=sessions.filter(s=>(filter==='All'||s.type===filter)&&s.title.toLowerCase().includes(query.toLowerCase()));
 html=`<p class="greeting">YOUR PERSONAL COLLECTION</p><h1>Your library.</h1><p class="caption muted">Every session, a chance to see something new.</p><input id="search" aria-label="Search sessions" placeholder="Search your sessions" value="${escape(query)}"><div class="segmented">${['All','Match','Practice'].map(f=>button('filter',f,' '+(filter===f?'selected':''),`data-filter="${f}"`)).join('')}</div>${list.map(sessionRow).join('')||empty('A little quiet on court',sessions.length?'No sessions match this filter.':'Your videos will live here. Add your first session.')} ${button('add',icon('plus')+' Add a video')}${privacy()}`;
 }
 if(current==='report'&&s)html=`<p class="greeting">${escape(s.type.toUpperCase())} · ${date(s.date)} · ${time(s.duration)}</p><h1>${escape(s.title)}</h1>${button('play',icon('play')+' Play your video','primary',`data-id="${s.id}" data-seconds="0"`)}${notice()}${s.report?`<div class="section-head"><h2>Your next-session focus</h2><span class="eyebrow" style="font-size:8px">3 IDEAS</span></div>${s.report.insights.map(i=>button('insight',`<div class="insight-top"><span class="badge">PRIORITY 0${i.priority}</span><span class="caption muted">${escape(i.category)}</span></div><h3>${escape(i.title)}</h3><div class="metric">${i.value}${escape(i.unit)}<span>${escape(i.metric)}</span></div><p class="caption muted">EXAMPLE STATISTIC · NOT MEASURED FROM YOUR VIDEO</p><div class="insight-foot"><span>${i.moments.length} sample review points · Explore</span>${icon('arrow')}</div>`,'card insight',`data-key="${escape(i.key)}"`)).join('')}`:button('retry','Generate sample insights')} ${button('delete-session',icon('trash')+' Delete this session','delete',`data-id="${s.id}"`)}`;
 if(current==='insight'&&s){
 const i=s.report.insights.find(i=>i.key===activeKey);
 html=`<p class="greeting">${escape(i.category.toUpperCase())} · SAMPLE COACHING</p><h1>${escape(i.title)}</h1><p class="caption muted">${escape(i.description)}</p><div class="card drill"><span class="eyebrow">TAKE THIS TO THE COURT</span><h2>${escape(i.cue)}</h2><p>${escape(i.drill)}</p>${button('save-drill',icon(saved.includes(i.key)?'check':'plus')+(saved.includes(i.key)?' Saved to your plan':' Save this drill'),'primary lime',`data-key="${escape(i.key)}"`)}</div><a class="pill-link" href="${safeYoutube(i.youtubeURL)}" target="_blank" rel="noopener noreferrer">${icon('play')} ${i.youtubeURL.includes('/watch?')?'Watch the technique lesson':'Find this drill on YouTube'} ${icon('arrow')}</a><p class="caption muted">${i.youtubeURL.includes('/watch?')?'Opens a technique lesson on YouTube.':'Opens YouTube search results for this technique.'}</p><div class="section-head"><h2>Across your videos</h2></div><p class="caption muted">Illustrative timestamps, not detected mistakes. Watch and make your own observations.</p>${sessions.filter(v=>v.report?.insights.some(x=>x.key===i.key)).map(v=>`<div class="card"><h3>${escape(v.title)}</h3><p class="caption muted">${date(v.date)} · ${escape(v.type)} · On this device</p>${v.report.insights.find(x=>x.key===i.key).moments.map(m=>button('play',icon('play')+`<time>${time(m.seconds)}</time><span>${escape(m.label)}</span>${icon('right')}`,'moment',`data-id="${v.id}" data-seconds="${m.seconds}"`)).join('')}</div>`).join('')}<h3>Your own observations</h3><label for="note" class="muted">What did you notice in this session?</label><textarea id="note" placeholder="For example: I felt rushed on my backhand today…">${escape(s.notes?.[i.key]||'')}</textarea>${button('save-note','Save note','secondary','style="margin-top:12px"')}`;
 }
 if(current==='improve'){
 const unique=new Map();for(const s of sessions)for(const i of s.report?.insights||[])if(saved.includes(i.key)&&!unique.has(i.key))unique.set(i.key,i);
 html=`<p class="greeting">YOUR NEXT SESSION STARTS HERE</p><h1>Small habits.<br>Stronger tennis.</h1><p class="caption muted">Your saved cues, ready for the court. Pick one to make your focus today.</p>${[...unique.values()].map(i=>`<div class="card drill"><span class="eyebrow">${escape(i.category)}</span><h2>${escape(i.cue)}</h2><p>${escape(i.drill)}</p><a class="pill-link" href="${safeYoutube(i.youtubeURL)}" target="_blank" rel="noopener noreferrer">${icon('play')} Find a tutorial ↗</a>${button('save-drill','Remove from plan','plain',`data-key="${escape(i.key)}"`)}</div>`).join('')||empty('One focus at a time','Save a drill from a session report. Your personal practice plan will appear here.','target')}${privacy()}`;
 }
 if(current==='profile')html=`<p class="greeting">YOUR SPACE, YOUR GAME</p><h1>${escape(guest?'Hey, player.':profile?.name||'Your profile.')}</h1><div class="settings"><div class="card"><div class="setting-title">${icon('user')} ${guest?'Guest player':'Device account'}</div><p>${escape(guest?'No account required to use your library.':profile?.email||'')}</p><p>Local to this browser. No cloud account, email verification or password recovery. Guest mode and your device account share this library; login is an experience demo, not a privacy boundary.</p>${!profile?button('signup','Create device account','plain'):''}${button('signout','Sign out','plain')}</div><div class="card"><div class="setting-title">${icon('lock')} Your videos stay yours</div><p>Videos are stored in this browser’s local database. No video, audio, filename, notes or account details are sent to any server.</p><p>Only duration, session type and focus are sent to the insights API. The host receives ordinary connection data, such as IP address.</p><p>Browser storage can be cleared or evicted. Keep your original videos. The native iOS app keeps an on-device copy excluded from iCloud backup.</p></div><div class="card"><div class="setting-title">${icon('target')} Honest by design</div><p>Insights, statistics and timestamps are random examples. They do not describe your performance or identify mistakes. Your notes are your own observations.</p><p>General practice suggestions are educational; adapt to your ability and stop if something hurts.</p></div><div class="card"><div class="setting-title">${icon('trash')} Your data, your control</div><p>Delete your profile, imported copies, reports, saved drills and notes from this browser. Your original files are unchanged.</p>${button('delete-all','Delete account & all local data','delete')}</div><p class="caption muted">Ace Pro · Experience preview 0.2<br>One insights API. Zero video uploads.</p></div>`;
 shell(html);
}
function safeYoutube(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='www.youtube.com'?escape(url):'#'}catch{return '#'}}
function navigate(screen){current=screen;render();}
let priorFocus;
function modal(content){if(!$('#overlay').firstChild)priorFocus=document.activeElement;$('#app').inert=true;$('#overlay').innerHTML=`<div class="overlay"><section class="sheet" role="dialog" aria-modal="true" aria-label="Ace Pro dialog">${content}</section></div>`;$('#overlay').querySelector('input,button,video')?.focus();}
function closeModal(){flowID++;controller?.abort();controller=null;busy=false;$('#app').inert=false;$('#overlay').innerHTML='';if(playerURL){URL.revokeObjectURL(playerURL);playerURL=null;}priorFocus?.focus();}
function auth(mode){authMode=mode;modal(`<div class="sheet-head"><b>DEVICE ACCOUNT</b>${button('close','Cancel','plain')}</div><h1>${mode==='create'?'Make it yours.':'Welcome back.'}</h1><p>A local profile for this device. No email is sent or verified.</p><form id="auth-form">${mode==='create'?'<label for="name">Your name</label><input id="name" name="name" autocomplete="given-name" required maxlength="60">':''}<label for="email">Email</label><input id="email" name="email" type="email" autocomplete="username" required><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="${mode==='create'?'new-password':'current-password'}" minlength="8" required><div id="auth-error" role="alert"></div><button class="primary" type="submit">${mode==='create'?'Create device account':'Log in'}</button></form><p class="caption" style="margin-top:16px">${mode==='create'?'Use a unique password for this demo. It is salted and derived locally using PBKDF2; it never leaves this browser.':'No cloud password recovery. Guest mode still gives you access to your library. You can delete/reset this device’s profile in Settings.'}</p>`)}
async function derive(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new Uint8Array(salt),iterations:210000,hash:'SHA-256'},key,256)));}
function addModal(){flowID++;modal(`<div class="sheet-head"><b>NEW SESSION</b>${button('close','Cancel','plain')}</div><h1>A fresh look<br>at your game.</h1><p>Add a match or practice video to your private library.</p><form id="import-form"><label class="dropzone" for="video-file">${icon('upload')}<strong>Choose a video from your device</strong><span class="muted">Stored locally. Never uploaded.</span><input type="file" id="video-file" accept="video/*" required></label><label for="session-title">Session name</label><input id="session-title" placeholder="Sunday practice" maxlength="100"><label for="session-type">Session type</label><select id="session-type"><option>Practice</option><option>Match</option></select><label for="focus">What would you like to work on?</label><select id="focus"><option>All-round</option><option>Footwork</option><option>Technique</option><option>Serve</option><option>Tactics</option></select>${notice()}<div id="import-error" role="alert"></div><button class="primary" type="submit">Save & generate sample insights ${icon('arrow')}</button></form>${button('sample','No video handy? Create a local court demo','plain','style="width:100%;margin-top:12px"')}`)}
async function durationOf(file){return new Promise((resolve,reject)=>{const v=document.createElement('video'),url=URL.createObjectURL(file);const timeout=setTimeout(()=>finish(new Error('Could not read this video. Try an MP4 or MOV file.')),10000);function finish(error){clearTimeout(timeout);v.onloadedmetadata=null;v.onerror=null;v.removeAttribute('src');v.load();URL.revokeObjectURL(url);if(error)reject(error)}v.preload='metadata';v.onloadedmetadata=()=>{const n=v.duration;if(!Number.isFinite(n)||n<1||n>21600||v.videoWidth===0)return finish(new Error('Choose a playable video between 1 second and 6 hours.'));resolve(n);finish()};v.onerror=()=>finish(new Error('This browser cannot play that video. Try H.264 MP4.'));v.src=url;});}
function progress(stage,percent){modal(`<div class="sheet-head"><b>ON-DEVICE SESSION</b>${button('cancel-process','Cancel','plain')}</div><div class="processing"><div class="progress-ring">${icon('ball')}</div><h1 role="status" aria-live="polite">${stage}</h1><p>Your video stays right here.<br>We’re simulating the coaching experience.</p></div><div class="progress-list"><div class="done">✓ &nbsp; Video saved on this device</div><div class="${percent>40?'done':''}">${percent>40?'✓':'○'} &nbsp; Simulated movement review</div><div class="${percent>70?'done':''}">${percent>70?'✓':'○'} &nbsp; Prepare coaching priorities</div><div>○ &nbsp; Get a sample report from the API</div></div><div class="progress-track"><div style="width:${percent}%"></div></div><p class="caption" style="text-align:center;margin-top:20px">No video upload · Random example insights</p>`)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function analyze(id){
 const s=sessions.find(v=>v.id===id);if(!s)throw new Error('This session no longer exists.');const operation=++flowID;busy=true;const requestController=new AbortController();controller=requestController;const signal=requestController.signal;let timeout;
 try{
  for(const [stage,percent] of [['Finding your focus…',25],['Connecting the moments…',50],['Building your next session…',78]]){if(signal.aborted)return;progress(stage,percent);await wait(900)}
  if(signal.aborted)return;
  timeout=setTimeout(()=>requestController.abort(),30000);
  const response=await fetch('/api/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({durationSeconds:s.duration,sessionType:s.type,focus:s.focus}),signal});
  const report=await response.json();if(!response.ok)throw new Error(report.error||'The insights service is unavailable.');
  if(report.simulated!==true||report.schemaVersion!==1||report.insights?.length!==3||new Set(report.insights.map(i=>i.key)).size!==3||!report.insights.every(i=>Number.isFinite(i.value)&&i.value>=0&&i.value<=100&&i.moments.every(m=>Number.isFinite(m.seconds)&&m.seconds>=0&&m.seconds<s.duration)))throw new Error('The service returned an invalid report.');
  if(signal.aborted||operation!==flowID)return;s.report=report;await write('sessions',sessions);if(signal.aborted||operation!==flowID)return;busy=false;closeModal();activeID=id;navigate('report');toast('Sample report ready. Your video stayed local.');
 }catch(error){if(operation!==flowID)return;busy=false;modal(`<div class="sheet-head"><b>VIDEO SAVED SAFELY</b>${button('close','Done','plain')}</div><h1>Let’s try that again.</h1><p>${escape(error.name==='AbortError'?'The request timed out. Your video is still saved locally.':error.message)}</p>${button('retry','Retry sample insights')}`)}finally{clearTimeout(timeout);if(operation===flowID)busy=false}
}
async function importFile(file,metadata){
 const operation=flowID;const duration=await durationOf(file);if(operation!==flowID)return;const id=crypto.randomUUID();
 const s={id,date:Date.now(),title:metadata.title.trim()||`${metadata.type} session`,type:metadata.type,focus:metadata.focus,duration,notes:{}};
 await saveVideo(s,file);sessions.unshift(s);if(operation!==flowID){render();return}activeID=id;current='report';render();await analyze(id);
}
async function play(id,seconds){const s=sessions.find(v=>v.id===id),blob=await read('video:'+id);if(!blob){toast('This local video is missing. Please import it again.');return;}playerURL=URL.createObjectURL(blob);modal(`<div class="sheet-head"><b>LOCAL REPLAY · ${time(seconds)}</b>${button('close','Done','plain')}</div><video controls playsinline src="${playerURL}" aria-label="${escape(s.title)}"></video><h2>${escape(s.title)}</h2><p>Sample review point at ${time(seconds)}. This is not a detected mistake. Use the controls to inspect your technique.</p>${privacy()}`);const v=$('#overlay video');v.addEventListener('loadedmetadata',()=>{v.currentTime=seconds;v.play().catch(()=>{});},{once:true});v.addEventListener('error',()=>toast('This browser cannot play the saved video. Try an MP4 file.'));}
async function sample(){
 if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){toast('Your browser needs a real video. Choose an MP4 file.');return}
 controller=new AbortController();const signal=controller.signal;const b=$('[data-action="sample"]');b.disabled=true;b.textContent='Creating a local court animation…';
 const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(24);const mime=['video/webm;codecs=vp9','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));
 const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(r=>recorder.onstop=r);let frame=0;
 const draw=()=>{ctx.fillStyle='#173f31';ctx.fillRect(0,0,960,540);ctx.strokeStyle='#c2d6b7';ctx.lineWidth=3;ctx.strokeRect(170,60,620,420);ctx.strokeRect(230,60,500,420);ctx.strokeRect(230,160,500,220);ctx.beginPath();ctx.moveTo(480,160);ctx.lineTo(480,380);ctx.moveTo(140,270);ctx.lineTo(820,270);ctx.stroke();ctx.fillStyle='#d7ed92';ctx.beginPath();ctx.arc(480+180*Math.sin(frame/20),270+155*Math.cos(frame/15),12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7efd8';ctx.font='18px sans-serif';ctx.fillText('ACE PRO · LOCAL DEMO ANIMATION · NOT MATCH FOOTAGE',170, 30);frame++;};
 draw();recorder.start();const interval=setInterval(draw,1000/24);await wait(4200);recorder.stop();await stopped;clearInterval(interval);stream.getTracks().forEach(t=>t.stop());if(signal.aborted)return;
 // WebM MediaRecorder files may omit duration; the known animation duration is retained below.
 const file=new Blob(chunks,{type:recorder.mimeType});const id=crypto.randomUUID();const s={id,date:Date.now(),title:'Court movement · demo',type:'Practice',focus:'Footwork',duration:4.2,notes:{}};
 await saveVideo(s,file);sessions.unshift(s);if(signal.aborted){render();return}activeID=id;current='report';render();await analyze(id);
}
document.addEventListener('submit',async event=>{
 event.preventDefault();const form=event.target;
 if(form.id==='auth-form'){
  const data=new FormData(form),email=data.get('email').trim().toLowerCase(),password=data.get('password');const submit=form.querySelector('[type="submit"]');submit.disabled=true;
  try{if(authMode==='create'){if(profile)throw new Error('An account already exists on this device. Log in or use guest mode.');const name=data.get('name').trim();if(!name)throw new Error('Please enter your name.');const salt=Array.from(crypto.getRandomValues(new Uint8Array(32)));profile={name,email,salt,hash:await derive(password,salt)};await write('profile',profile)}else{if(!profile||profile.email!==email)throw new Error('Email or password does not match this device’s account.');const hash=await derive(password,profile.salt);if(hash.some((n,i)=>n!==profile.hash[i]))throw new Error('Email or password does not match this device’s account.')}guest=false;closeModal();navigate('home')}catch(error){$('#auth-error').innerHTML=`<div class="error">${escape(error.message)}</div>`;submit.disabled=false;await reload()}
 }
 if(form.id==='import-form'){
  const file=$('#video-file').files[0];if(!file)return;const metadata={title:$('#session-title').value,type:$('#session-type').value,focus:$('#focus').value};const submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Saving on this device…';
  try{await importFile(file,metadata)}catch(error){if($('#import-error'))$('#import-error').innerHTML=`<div class="error">${escape(error.message)}</div>`;else toast(error.message);submit.disabled=false;submit.textContent='Save & generate sample insights';}
 }
});
document.addEventListener('input',e=>{if(e.target.id==='search'){const start=e.target.selectionStart;query=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(start,start);}});
document.addEventListener('click',async event=>{
 const el=event.target.closest('[data-action]');if(!el)return;
 const action=el.dataset.action;
 try{
 if(['home','library','improve','profile','report'].includes(action))navigate(action);
 else if(action==='guest'){guest=true;navigate('home')}
 else if(action==='signup')auth('create');else if(action==='login')auth('login');
 else if(action==='close'||action==='cancel-process'){closeModal();render()}
 else if(action==='signout'){guest=false;navigate('welcome')}
 else if(action==='add')addModal();else if(action==='sample')await sample();
 else if(action==='open-report'){activeID=el.dataset.id;navigate('report')}
 else if(action==='insight'){activeKey=el.dataset.key;navigate('insight')}
 else if(action==='filter'){filter=el.dataset.filter;render()}
 else if(action==='play')await play(el.dataset.id,Number(el.dataset.seconds));
 else if(action==='retry')await analyze(activeID);
 else if(action==='save-drill'){const key=el.dataset.key;saved=saved.includes(key)?saved.filter(x=>x!==key):[...saved,key];await write('saved',saved);render();toast(saved.includes(key)?'Drill saved to your practice plan':'Drill removed')}
 else if(action==='save-note'){const s=sessions.find(v=>v.id===activeID);s.notes={...s.notes,[activeKey]:$('#note').value};await write('sessions',sessions);toast('Your observation is saved on this device')}
 else if(action==='delete-session'){modal(`<div class="sheet-head"><b>DELETE SESSION</b>${button('close','Cancel','plain')}</div><h1>Remove this session?</h1><p>This deletes the local video copy, report and notes. The original file is unchanged.</p>${button('confirm-delete-session','Delete session','primary',`data-id="${el.dataset.id}"`)}`)}
 else if(action==='confirm-delete-session'){const id=el.dataset.id;await remove('video:'+id);sessions=sessions.filter(s=>s.id!==id);await write('sessions',sessions);const remaining=new Set(sessions.flatMap(s=>(s.report?.insights||[]).map(i=>i.key)));saved=saved.filter(key=>remaining.has(key));await write('saved',saved);closeModal();navigate('library');toast('Session deleted')}
 else if(action==='delete-all')modal(`<div class="sheet-head"><b>DELETE ALL LOCAL DATA</b>${button('close','Cancel','plain')}</div><h1>A clean slate?</h1><p>This permanently deletes your device account, imported copies, reports, notes and drills from this browser. Your original files stay unchanged.</p>${button('confirm-delete-all','Delete account & all local data','primary')}`);
 else if(action==='confirm-delete-all'){await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});await reload();closeModal();guest=false;navigate('welcome');toast('Account and local data deleted')}
 }catch(error){toast(error.message||'Something went wrong. Please try again.')}
});
document.addEventListener('keydown',event=>{if(!$('#overlay').firstChild)return;if(event.key==='Escape'){closeModal();render()}if(event.key==='Tab'){const controls=[...$('#overlay').querySelectorAll('button:not(:disabled),input,select,textarea,a[href],video')];const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});
render();
